package Mapeamento;
// Generated 05/06/2019 09:01:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbCliente generated by hbm2java
 */
@Entity
@Table(name="tb_cliente"
    ,schema="projeto"
)
public class TbCliente  implements java.io.Serializable {


     private String cpf;
     private String nomecli;
     private String emailcli;
     private String estadocli;
     private String ruacli;
     private String cidadecli;
     private String bairrocli;
     private Integer numerocli;
     private Boolean tipo;
     private String senhacli;
     private Set<TbCompra> tbCompras = new HashSet(0);

    public TbCliente() {
    }

	
    public TbCliente(String cpf) {
        this.cpf = cpf;
    }
    public TbCliente(String cpf, String nomecli, String emailcli, String estadocli, String ruacli, String cidadecli, String bairrocli, Integer numerocli, Boolean tipo, String senhacli, Set<TbCompra> tbCompras) {
       this.cpf = cpf;
       this.nomecli = nomecli;
       this.emailcli = emailcli;
       this.estadocli = estadocli;
       this.ruacli = ruacli;
       this.cidadecli = cidadecli;
       this.bairrocli = bairrocli;
       this.numerocli = numerocli;
       this.tipo = tipo;
       this.senhacli = senhacli;
       this.tbCompras = tbCompras;
    }
   
     @Id 

    
    @Column(name="cpf", unique=true, nullable=false)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    
    @Column(name="senhacli", length=20)
    public String getSenhacli() {
        return this.senhacli;
    }
    
    public void setSenhacli(String senhacli) {
        this.senhacli = senhacli;
    }

    
    @Column(name="nomecli", length=50)
    public String getNomecli() {
        return this.nomecli;
    }
    
    public void setNomecli(String nomecli) {
        this.nomecli = nomecli;
    }

    
    @Column(name="emailcli", length=100)
    public String getEmailcli() {
        return this.emailcli;
    }
    
    public void setEmailcli(String emailcli) {
        this.emailcli = emailcli;
    }

    
    @Column(name="estadocli", length=20)
    public String getEstadocli() {
        return this.estadocli;
    }
    
    public void setEstadocli(String estadocli) {
        this.estadocli = estadocli;
    }

    
    @Column(name="ruacli", length=50)
    public String getRuacli() {
        return this.ruacli;
    }
    
    public void setRuacli(String ruacli) {
        this.ruacli = ruacli;
    }

    
    @Column(name="cidadecli", length=50)
    public String getCidadecli() {
        return this.cidadecli;
    }
    
    public void setCidadecli(String cidadecli) {
        this.cidadecli = cidadecli;
    }

    
    @Column(name="bairrocli", length=50)
    public String getBairrocli() {
        return this.bairrocli;
    }
    
    public void setBairrocli(String bairrocli) {
        this.bairrocli = bairrocli;
    }

    
    @Column(name="numerocli")
    public Integer getNumerocli() {
        return this.numerocli;
    }
    
    public void setNumerocli(Integer numerocli) {
        this.numerocli = numerocli;
    }

    
    @Column(name="tipo")
    public Boolean getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Boolean tipo) {
        this.tipo = tipo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbCliente")
    public Set<TbCompra> getTbCompras() {
        return this.tbCompras;
    }
    
    public void setTbCompras(Set<TbCompra> tbCompras) {
        this.tbCompras = tbCompras;
    }




}


